In [1]:
import pandas as pd

In [2]:
# Cleaning Data
df = pd.read_csv("raw_data.csv") 

# Handle Missing values
df.isnull()            # True for null values (NaN)
df.isnull().sum()      # counts missing vals per column

df.dropna()            # drops rows with missing values
df.dropna(axis = 1)    # drops cols with missing values

df.fillna(0)           # fills NaN with value

cleaning_data=df.copy()
mean_age=cleaning_data["age"].mean()
cleaning_data["age"]=cleaning_data["age"].fillna(mean_age)  # fills column with mean
cleaning_data

df.ffill()             # forward fill
df.bfill()             # backward fill

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [3]:
# Handle Duplicate values

df.duplicated()                      # True for duplicate rows
df.duplicated("country")             # True for duplicate rows in particular col
df.duplicated(["country", "gender"]) 

df.drop_duplicates()                 # drops duplicate rows
# df.drop_duplicates(inplace=True)   # drops the duplicate rows in original data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [4]:
# Handle Data Types
df.dtypes                                     # dtype of each col
df2=df.copy()
df2["age"]=df2["age"].fillna(0)
df2["age"] = df2["age"].astype("int64")       # change dtype
df2.dtypes

date_data=pd.Series([pd.to_datetime("2026-12-25")])
type(date_data.dtypes)

numpy.dtypes.DateTime64DType

In [5]:
# String type
df2["gender"].str.lower()                      # lower case
df2["gender"].str.upper()                      # upper case
df2["gender"].str.capitalize()                 # capitalize
df2["name"].str.split(" ")                     # splits into lists based on separator value 

df2["country"].str.contains("US")
df2["country"].str.contains("india", case=False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

In [6]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0