In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("raw_data.csv")

In [3]:
# Transformation / Feature Engineering
df2 = df.copy()

# apply a fnx to a row or col
df2["tax"]=df2["income"].apply(lambda x: "20%" if x>=60_000 else "10%")

# map values to another
new_gender_vals={"Male":"M","Female":"F","Unknown":"UNK"}
df2["gender"]=df2["gender"].map(new_gender_vals)

# assign some new values
df2=df2.assign(new_income=df2["income"]*1.1)

# replace specific values
df2["country"]=df2["country"].replace("USA","US")

In [4]:
df2

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN      US    UNK  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0

In [ ]:
# Transformation - Sorting

# Renaming
df2.columns = ["Id", "Name", "Age", "Country", "Gender", "Income"]
df2.rename(columns={"Income": "Salary"})
df2.rename(index={0: "first"})

# Sorting - values & index
df2.sort_values("Income")                     # sort values in ascending
df2.sort_values("Income", ascending=False)    # sort values in descending
df2.sort_values(["Age", "Income"])            # sorts for age, if age is same then sorts for income 

sorted_df2 = df2.sort_values(["Age", "Income"])
sorted_df2.sort_index()

# Reset Index
sorted_df2.reset_index()
sorted_df2.reset_index(drop=True)     # to drop original index vals

# Ranking
df2["Ranking"] = df2["Income"].rank(ascending=False, method="dense")

# Reorder
df2[["Id", "Name", "Age", "Income", "Gender", "Country", "Ranking"]]

In [5]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0