In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("raw_data.csv")

In [3]:
# Transformation / Feature Engineering
df2 = df.copy()

# apply a fnx to a row or col
df2["tax"]=df2["income"].apply(lambda x: "20%" if x>=60_000 else "10%")

# map values to another
new_gender_vals={"Male":"M","Female":"F","Unknown":"UNK"}
df2["gender"]=df2["gender"].map(new_gender_vals)

# assign some new values
df2=df2.assign(new_income=df2["income"]*1.1)

# replace specific values
df2["country"]=df2["country"].replace("USA","US")

In [4]:
df2

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN      US    UNK  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0

In [ ]:
# Transformation - Sorting

# Renaming
df2.columns=["Id","Name","Age","Country","Gender","Income","Tax","New_Income"]
df2=df2.rename(columns={"Income":"Salary"})
# df2=df2.rename(index={1:"first"})

# # Sorting - values & index
df2.sort_values("Salary")                      # sort values in ascending
df2.sort_values("Salary",ascending=False)      # sort values in descending
df2["Age"]=df2["Age"].fillna(50)
sorted_df2=df2.sort_values(["Salary","Age"])   # sorts for salary, if salary is same then sorts for age  

sorted_df2.sort_index()                        # sorts the index so back to normal form

# Reset Index
sorted_df2.reset_index()                       # preserves the original index by making the new column "index" and introduce new index for table
sorted_df2.reset_index(drop=True)              # to drop original index vals

# # Ranking
df2["Ranking"] = df2["Salary"].rank(ascending=False, method="dense")
# df2["Ranking"] = df2["Salary"].rank(ascending=False, method="min")
# df2["Ranking"] = df2["Salary"].rank(ascending=False, method="max")

# # Reorder
df2[["Id", "Name", "Age", "Salary", "Ranking","Gender", "Country","Tax","New_Income"]]

    Id          Name   Age   Salary  Ranking Gender Country  Tax  New_Income
0    1      John Doe  29.0  55000.0      5.0      M      US  10%     60500.0
1    1      John Doe  29.0  55000.0      5.0      M      US  10%     60500.0
2    2    Jane Smith  50.0  62000.0      3.0      F  Canada  20%     68200.0
3    3          Alex  50.0  47000.0      7.0    UNK      US  10%     51700.0
4    4  Maria Garcia  34.0      NaN      NaN      F   Spain  10%         NaN
5    5        Li Wei  27.0  51000.0      6.0      M   China  10%     56100.0
6    6           NaN  45.0  73000.0      1.0      F   India  20%     80300.0
7    7    Ahmed Khan  38.0  68000.0      2.0      M     NaN  20%     74800.0
8    8    Rachel Lee  29.0  62000.0      3.0      F      US  20%     68200.0
9    9   Carlos Ruiz  50.0  45000.0      8.0      M  Mexico  10%     49500.0
10  10   Emily Davis  31.0  58000.0      4.0    NaN      US  10%     63800.0

In [6]:
df2

    Id          Name   Age Country Gender   Salary  Tax  New_Income  Ranking
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0      5.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0      5.0
2    2    Jane Smith  50.0  Canada      F  62000.0  20%     68200.0      3.0
3    3          Alex  50.0      US    UNK  47000.0  10%     51700.0      7.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN      NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0      6.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0      1.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0      2.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0      3.0
9    9   Carlos Ruiz  50.0  Mexico      M  45000.0  10%     49500.0      8.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0      4.0